apiVersion: apps/v1
kind: Deployment
metadata:
  name: productdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Product
  template:
    metadata:
      labels:
        app: Product
    spec:
      containers:
      - name: productrepository
        image: containerr1.azurecr.io/productrepository:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: redone

---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: Product
